char preLoad[] =
";; Rebel uses _ prefix for symbol names in functions and macros\n"
";;\n"
"\n"
";; language\n"
";; ---------------------------------------------------------------------\n"
"\n"
"; 0-based indexing\n"
"; slowly remove nth as misleading legacy name\n"
"(macex ith (N Xs)\n"
"  (nth N Xs))\n"
"\n"
"; 1-based indexing\n"
"(macex kth (N Xs)\n"
"  (nth (- N 1) Xs))\n"
"\n"
";; gentle bridge - not protected names, visible only in MAIN\n"
";; ---------------------------------------------------------------------\n"
"(mac (setf) \n"
"  (if (quote? (args 0)) \n"
"    (do \n"
"      (puts {Warn: quoted symbol used in function setf: } (args 0)) \n"
"      nil) \n"
"    (do \n"
"      (puts {Info: in Rebel use 'set/setn' for assignment.})\n"
"      (set (eval (args 0)) (args 1)))))\n"
"\n"
"(mac (setq) \n"
"  (if (quote? (args 0)) \n"
"    (do \n"
"      (puts {Warn: quoted symbol used in function setq: } (args 0)) \n"
"      nil) \n"
"    (do \n"
"      (puts {Info: in Rebel use 'set/setn' for assignment.})\n"
"      (set (eval (args 0)) (args 1)))))\n"
"\n"
";; convenience\n"
";; ---------------------------------------------------------------------\n"
"(func (hash)\n"
"  ; context based hash using unique context name\n"
"  ; (set db (hash))\n"
"  (set _hash-tpl:_hash-tpl)\n"
"  (clone _hash-tpl (sym (string \"hash-\" (mstime))) true))\n"
"\n"
"(func (printf) \n"
"  (print (format (args 0) (expand (rest (args)))))) \n"
"\n"
";; deprecated/removed functions    \n"
";; ---------------------------------------------------------------------\n"
";(func (cond) \n"
"; {Info: in Rebel use multi-branch 'if/ifnot' instead of 'cond'.}) \n"
"\n"
";; list of contents\n"
";; ---------------------------------------------------------------------\n"
"(set $preload '(\n"
"\n"
"    hash\n"
"    ith\n"
"    kth\n"
"    printf \n"
"    setf\n"
"    setq\n"
"\n"
"  )\n"
")\n"
"\n"
";; Only some are protected and visible in all contexts\n"
";; ---------------------------------------------------------------------\n"
"(const (shared \n"
"\n"
"  '$preload\n"
"  'hash\n"
"  'ith\n"
"  'kth\n"
"  'printf\n"
"\n"
"))\n"
"\n"
;
