char preLoad[] =
";; Rebel uses _ prefix for symbol names in functions and macros\n"
";;\n"
";; temporary compatibility and deprecated or removed functions\n"
";; ---------------------------------------------------------------------\n"
"(func (printf) \n"
"  (print (format (args 0) (expand (rest (args)))))) \n"
"\n"
"(mac (setf) \n"
"  (if (quote? (args 0)) \n"
"    (do \n"
"      (puts {Warn: quoted symbol used in function setf: } (args 0)) \n"
"      nil) \n"
"    (do \n"
"      (puts {Info: in Rebel use 'set' for variable assignment.})\n"
"      (set (eval (args 0)) (args 1)))))\n"
"    \n"
"(mac (cond) \n"
"  (puts {Info: in Rebel use multi-branch 'if/ifnot' instead of 'cond'.}) nil) \n"
"\n"
"(func (hash)\n"
"  (set _hash-tpl:_hash-tpl)\n"
"  (clone _hash-tpl (sym (string \"hash-\" (uuid))) true))\n"
"\n"
";; list of contents\n"
";; ---------------------------------------------------------------------\n"
"(set $preload '(\n"
"    cond \n"
"    hash\n"
"    printf \n"
"    setf\n"
"  )\n"
")\n"
"\n"
";; make it visible in all contexts\n"
";; ---------------------------------------------------------------------\n"
"(const (shared \n"
"  'cond\n"
"  'hash\n"
"  'printf\n"
"  'setf\n"
"  '$preload\n"
"))\n"
"\n"
;
