char preLoad[] =
";; temporary compatibility and deprecated or removed functions\n"
";; ---------------------------------------------------------------------\n"
"(func (printf) \n"
"  (print (format (args 0) (expand (rest (args)))))) \n"
"\n"
"(mac (setf) \n"
"  (if (quote? (args 0)) \n"
"    (do \n"
"      (puts {Warn: quoted symbol used in function setf: } (args 0)) \n"
"      nil) \n"
"    (do \n"
"      (puts {Info: in Rebel use 'set' for variable assignment.})\n"
"      (set (eval (args 0)) (args 1)))))\n"
"    \n"
"(mac (cond) \n"
"  (puts {Info: in Rebel use multi-branch 'if/ifnot' instead of 'cond'.}) nil) \n"
"\n"
";; ext functions and macros with dot domain prefix\n"
";; ---------------------------------------------------------------------\n"
"\n"
";; handy list of contents\n"
";; ---------------------------------------------------------------------\n"
"(set $preload '(cond printf setf))\n"
"\n"
";; make it visible in all contexts\n"
";; ---------------------------------------------------------------------\n"
"(const (shared \n"
"  'printf\n"
"  'setf\n"
"  'cond\n"
"  '$preload\n"
"))\n"
"\n"
;
